/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLASES;

import javax.swing.JOptionPane;

/**
 *
 * @author jdavi
 */
public class Ventana extends javax.swing.JInternalFrame {
int c=0, c2=0;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        opt_suma = new javax.swing.JRadioButton();
        opt_resta = new javax.swing.JRadioButton();
        opt_multi = new javax.swing.JRadioButton();
        opt_divis = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btn_suma = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_divis = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn_calcular = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        LBL_resultado = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jButton6.setText("jButton6");

        jButton5.setText("jButton5");

        setClosable(true);

        jPanel4.setPreferredSize(new java.awt.Dimension(150, 143));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(opt_suma);
        opt_suma.setSelected(true);
        opt_suma.setText("Suma");
        opt_suma.setEnabled(false);
        jPanel4.add(opt_suma);

        buttonGroup1.add(opt_resta);
        opt_resta.setText("resta");
        opt_resta.setEnabled(false);
        opt_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_restaActionPerformed(evt);
            }
        });
        jPanel4.add(opt_resta);

        buttonGroup1.add(opt_multi);
        opt_multi.setText("multiplicacion");
        opt_multi.setEnabled(false);
        jPanel4.add(opt_multi);

        buttonGroup1.add(opt_divis);
        opt_divis.setText("divicion");
        opt_divis.setEnabled(false);
        jPanel4.add(opt_divis);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 143));
        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        btn_suma.setText("suma");
        btn_suma.setEnabled(false);
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_suma);

        btn_resta.setText("resta");
        btn_resta.setEnabled(false);
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_resta);

        btn_multi.setText("multiplicacion");
        btn_multi.setEnabled(false);
        btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiActionPerformed(evt);
            }
        });
        jPanel5.add(btn_multi);

        btn_divis.setText("divicion");
        btn_divis.setEnabled(false);
        btn_divis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisActionPerformed(evt);
            }
        });
        jPanel5.add(btn_divis);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(429, 140));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jLabel2.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabel2.setText("Operaciones Aritmeticas ");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 22));
        jLabel2.setPreferredSize(new java.awt.Dimension(194, 100));
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9);

        jPanel8.setLayout(new java.awt.GridLayout(1, 1));

        btn_calcular.setText("calcular");
        btn_calcular.setEnabled(false);
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        jPanel8.add(btn_calcular);

        jPanel3.add(jPanel8);

        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        btn_cerrar.setText("cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(btn_cerrar);

        jPanel3.add(jPanel7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);

        txtNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero1ActionPerformed(evt);
            }
        });
        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumero1);

        txtNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero2ActionPerformed(evt);
            }
        });
        txtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero2KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumero2);

        jPanel11.setLayout(new java.awt.GridLayout(1, 1));

        LBL_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_resultado.setText("0.0");
        jPanel11.add(LBL_resultado);

        jPanel1.add(jPanel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1ActionPerformed

    private void txtNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2ActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
 String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "Hola");
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a * b;
               LBL_resultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a * b;
                LBL_resultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a * b;
                LBL_resultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a * t;
               LBL_resultado.setText(Float.toString(r));
          }
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
 String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "Hola");
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a - b;
               LBL_resultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a - b;
                LBL_resultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a - b;
                LBL_resultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a - t;
               LBL_resultado.setText(Float.toString(r));
          }
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
// TODO add your handling code here:
String n1 = txtNumero1.getText();
String n2 = txtNumero2.getText();

if (opt_suma.isSelected()){
 int a= Integer.parseInt(n1);
 int b= Integer.parseInt(n2);
 int c= a+b;
 LBL_resultado.setText(Integer.toString(c));
}

if (opt_resta.isSelected()){
 int a= Integer.parseInt(n1);
 int b= Integer.parseInt(n2);
 int c= a-b;
 LBL_resultado.setText(Integer.toString(c));
}

if (opt_multi.isSelected()){
 int a= Integer.parseInt(n1);
 int b= Integer.parseInt(n2);
 int c= a*b;
 LBL_resultado.setText(Integer.toString(c));
}

if (opt_divis.isSelected()){
 float a= Float.parseFloat(n1);
 float b= Float.parseFloat(n2);
 float c= a/b;
 LBL_resultado.setText(Float.toString(c));
}
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
    // TODO add your handling code here:
    this.hide();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void txtNumero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyTyped
        // TODO add your handling code here:
     int key= evt.getKeyChar(); //convertir un char a ascii
     if (key==8){ c--;
      } 
     if(c<0){
     c=0;
             }
     
     if ((key >=48 && key<=57) || key==46){
         c++;
     } else {  evt.consume(); }
              if (c>0 && c2>0){
    btn_suma.setEnabled(true);
    btn_resta.setEnabled(true);
    btn_multi.setEnabled(true);
    btn_divis.setEnabled(true);
    opt_suma.setEnabled(true);
    opt_resta.setEnabled(true);
    opt_divis.setEnabled(true);
    opt_multi.setEnabled(true);
    btn_calcular.setEnabled(true);
} else{
      btn_suma.setEnabled(false);
    btn_resta.setEnabled(false);
    btn_multi.setEnabled(false);
    btn_divis.setEnabled(false);
     opt_suma.setEnabled(false);
    opt_resta.setEnabled(false);
    opt_divis.setEnabled(false);
    opt_multi.setEnabled(false);
    btn_calcular.setEnabled(false);
}
      
    }//GEN-LAST:event_txtNumero1KeyTyped

    private void txtNumero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyTyped
    int key= evt.getKeyChar(); //convertir un char a ascii
     if (key==8){ c2--;
      } 
     if(c2<0){
     c2=0; }
     
     if ((key >=48 && key<=57) || key==46){
         c2++;
     } else {  evt.consume(); }
              if (c2>0 && c>0){
    btn_suma.setEnabled(true);
    btn_resta.setEnabled(true);
    btn_multi.setEnabled(true);
    btn_divis.setEnabled(true);
     opt_suma.setEnabled(true);
    opt_resta.setEnabled(true);
    opt_divis.setEnabled(true);
    opt_multi.setEnabled(true);
    btn_calcular.setEnabled(true);
} else{
      btn_suma.setEnabled(false);
    btn_resta.setEnabled(false);
    btn_multi.setEnabled(false);
    btn_divis.setEnabled(false);
    opt_suma.setEnabled(false);
    opt_resta.setEnabled(false);
    opt_divis.setEnabled(false);
    opt_multi.setEnabled(false);
    btn_calcular.setEnabled(false);
}
    // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2KeyTyped

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // >?<-_TODO add your handling code here:
         String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "Hola");
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a + b;
               LBL_resultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a + b;
                LBL_resultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a + b;
                LBL_resultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a + t;
               LBL_resultado.setText(Float.toString(r));
          }
        
        }
        
    
    
    
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_divisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisActionPerformed
 String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "Hola");
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a / b;
               LBL_resultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                float b = Float.parseFloat(n2);
                float r = a / b;
                LBL_resultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            float  a = Float.parseFloat(n1);
            if (v.validarEnteros(n2).equals("entero")){
                float  b = Float.parseFloat(n2);
                float r = a / b;
                LBL_resultado.setText(Float.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a / t;
               LBL_resultado.setText(Float.toString(r));
          }
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_divisActionPerformed

    private void opt_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_restaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt_restaActionPerformed
    
     
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_resultado;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_divis;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton opt_divis;
    private javax.swing.JRadioButton opt_multi;
    private javax.swing.JRadioButton opt_resta;
    private javax.swing.JRadioButton opt_suma;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    // End of variables declaration//GEN-END:variables
}
